services:
  - type: web
    name: frank-electronics
    env: static
    rootDir: frank_electronics
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /products
        destination: /products.html
      - type: rewrite
        source: /product
        destination: /product.html
      - type: rewrite
        source: /deals
        destination: /deals.html
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /contact
        destination: /contact.html
      - type: rewrite
        source: /checkout
        destination: /checkout.html
      - type: rewrite
        source: /wishlist
        destination: /wishlist.html
      - type: rewrite
        source: /login
        destination: /login.html
      - type: rewrite
        source: /register
        destination: /register.html
      - type: rewrite
        source: /otp
        destination: /otp.html
      - type: rewrite
        source: /forgot
        destination: /forgot.html
      - type: rewrite
        source: /reset-password
        destination: /reset-password.html
      - type: rewrite
        source: /profile
        destination: /profile.html
      - type: rewrite
        source: /admin
        destination: /admin.html
      - type: rewrite
        source: /*
        destination: /index.html